version: '9.9.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5175:5175"
    command: [ "yarn", "dev" ]

#docker-compose up --build
